apiVersion: 1
providers:
  - name: Torob Rent
    orgId: 1
    folder: Torob Rent
    folderUid: torob-rent
    type: file
    disableDeletion: true
    allowUiUpdates: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/dashboards/torob-rent
      foldersFromFilesStructure: false
