import { pgTable, uuid, text, timestamp, bigint, integer, boolean, jsonb, date } from "drizzle-orm/pg-core";
export const listings = pgTable("listings", {
  id: uuid("id").primaryKey(),
  workspaceId: uuid("workspace_id").notNull(),
  ownerId: uuid("owner_id").notNull(),
  title: text("title").notNull(),
  model: text("model").notNull(),
  chip: text("chip"),
  ram: integer("ram"),
  storage: integer("storage"),
  description: text("description").notNull(),
  condition: text("condition").notNull(),
  accessories: jsonb("accessories").notNull(),
  neighborhood: text("neighborhood").notNull(),
  dailyPrice: bigint("daily_price", { mode: "number" }).notNull(),
  deposit: bigint("deposit", { mode: "number" }).notNull(),
  minDays: integer("min_days").notNull(),
  guarantee: text("guarantee").notNull(),
  availableFrom: date("available_from").notNull(),
  availableTo: date("available_to").notNull(),
  blocked: jsonb("blocked").notNull(),
  photos: jsonb("photos").notNull(),
  status: text("status").notNull(),
  synthetic: boolean("synthetic").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});
